<?php
$order = array(
    "date_desc" => "Date Desc",
    "date_asc" => "Date Asc",
    "title_desc" => "Title Desc",
    "title_asc" => "Title Asc",
    "random" => "Random",
);
$eva_pbHeadSettings = array(
    "item_title" => array(
        "title"   => "Insert title here",
        "type"    => "text",
        "holder"  => "",
        "default" => "",
        "desc"    => "Insert title here",
    ),
    "item_title_alignment" => array(
        "title"   => "Alignment",
        "type"    => "select",
		"options" => array("left"=>"Left","center"=>"Center","right"=>"Right"),
		"holder"  => "",
		"default" => "center",
    ),
	"item_title_size" => array(
        "title"   => "Size",
        "type"    => "select",
		"options" => array("h1"=>"H1","h2"=>"H2","h3"=>"H3","h4"=>"H4","h5"=>"H5","h6"=>"H6"),
		"holder"  => "",
		"default" => "h2",
    ),
);
$eva_pbItems = array(
    "accordion" => array(
        "name"    => "Accordion",
        "size"    => "size-1-3",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "type"    => "button",
                "data"    => array("item"=>"accordion","settings"=>"items"),
                "default" => "Add Accordion",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "item_title",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "item_title" => array(
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "Accordion Title",
                        ),
                        "item_expand" => array(
                            "title"   => "Expand item",
                            "type"    => "checkbox",
                            "default" => "false",
                            "desc"    => "",
                        ),
                        "item_content" => array(
                            "type"    => "textArea",
                            "holder"  => "",
                            "default" => "Accordion content",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
            ),
        ),
    ),
	"before_after" => array(
		"name" => "Before After",
		"size" => "size-1-1",
		"settings" => array(
			"before" => array(
				"title" => "Before Image",
				"type" => "text",
				"holder" => "",
				"default" => "",
				"desc" => "This element will helps you compare the two images between. Please insert the before image here.",
			),
			"add_before" => array(
				"title" => "",
				"type" => "button",
				"save_to" => "before",
				"default" => "Upload",
				"desc" => "",
			),
			"after" => array(
				"title" => "After Image",
				"type" => "text",
				"holder" => "",
				"default" => "",
				"desc" => "Please insert the after image here.",
			),
			"add_after" => array(
				"title" => "",
				"type" => "button",
				"save_to" => "after",
				"default" => "Upload",
				"desc" => "",
			),
		),
	),
    "blog" => array(
        "name" => "Blog",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "only" => "builder",
        "settings" => array(
            "category" => array(
                "title"   => "Blog category",
                "type"    => "category",
                "options" => $post_categories,
                "default" => "0",
                "desc"    => "If you want to display Specify category then please choose.",
            ),
            "category_ids" => array(
                "type"    => "hidden",
                "selector"=> "category",
                "default" => "",
            ),
			"style" => array(
                "title"   => "Select style",
                "type"    => "select",
                "options" => array('medium_image'=>'Medium Image','masonry'=>'Masonry','full_width'=>'Full Width','carousel'=>'Carousel'),
				"hide"    => array("medium_image" => "columns","masonry" => "more_text2","full_width" => "more_text2","carousel" => "pagination,columns"),
                "default" => "medium_image",
                "desc"    => "",
            ),
			"columns" => array(
                "title"   => "choose columns quantity",
                "type"    => "select",
                "options" => array('col2'=>'2 Columns','col3'=>'3 Columns','col4'=>'4 Columns','col5'=>'5 Columns'),
                "default" => "col2",
                "desc"    => "",
            ),
            "post_count" => array(
                "title"   => "Post Count",
                "type"    => "text",
                "holder"  => "5",
                "default" => "5",
                "desc"    => "Insert how many posts will displayed in blog.",
            ),
            "pagination" => array(
                "title"   => "Pagination",
                "type"    => "select",
                "options" => $arrayYesNo,
                "default" => "false",
                "desc"    => "Enable or Disable blog pagination section.",
            ),
            "excerpt_count" => array(
                "title"   => "Excerpt Count",
                "type"    => "text",
                "holder"  => "60",
                "default" => "60",
                "desc"    => "How much blog words displayed in blog Excerpt.",
            ),
            "more_text" => array(
                "title"   => "Read more text",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert custom 'Read More' text",
            ),
			/*
			"more_text2" => array(
                "title"   => "Read more text",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert custom 'Read More' text",
            ),
			*/
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "button" => array(
        "name" => "Button",
        "only" => "shortcode",
        "content" => "text",
        "settings" => array(
            "text" => array(
                "title"   => "Button Text",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert button text.",
            ),
            "link" => array(
                "title"   => "Button link",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert button link url.",
            ),
            "size" => array(
                "title"   => "Button size",
                "type"    => "select",
                "options" => array("small"=>"Small","medium"=>"Medium","large"=>"Large"),
                "holder"  => "",
                "default" => "medium",
                "desc"    => "Select button size.",
            ),
			"fa" => array(
				"title"   => "Add Icon",
				"type"    => "fa",
				"holder"  => "",
				"default" => "",
				"desc"    => "",
			),
			"fa_icon" => array(
				"title"   => "Icon",
				"type"    => "hidden",
				"holder"  => "",
				"default" => "",
				"desc"    => "Icon.",
			),
            "bg_color" => array(
                "title"   => "Button color",
                "type"    => "color",
                "holder"  => "",
                "default" => "",
                "desc"    => "Choose button color.",
            ),
			"text_color" => array(
                "title"   => "Text color",
                "type"    => "color",
                "holder"  => "",
                "default" => "",
                "desc"    => "Choose text color.",
            ),
            "target" => array(
                "title"   => "Button target",
                "type"    => "select",
                "options" => $linkTarget,
                "holder"  => "",
                "default" => "_blank",
                "desc"    => "Select button target.",
            ),
        ),
    ),
    "column" => array(
        "name" => "Column",
        "size" => "size-1-3",
        "content" => "column_content",
        "only" => "builder",
        "settings" => array(
            "column_content" => array(
                "title"   => "",
                "type"    => "textArea",
                "tinyMCE" => "true",
                "holder"  => "",
                "default" => "Column Content",
                "desc"    => "",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "sh_column" => array(
        "name"    => "Column Shortcode",
        "size"    => "size-1-3",
        "only"      => "shortcode",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title"   => "Add Column",
                "type"    => "button",
                "data"    => array("item"=>"sh_column","settings"=>"items"),
                "default" => "Add Column",
                "desc"    => "Click to add column",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "column_size",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "column_size" => array(
                            "title"   => "Choose Column Size",
                            "type"    => "select",
                            "options" => array("1 / 4" => "1 / 4", "1 / 3" => "1 / 3", "1 / 2" => "1 / 2", "2 / 3" => "2 / 3", "3 / 4" => "3 / 4" , "1 / 1" => "1 / 1" ),
                            "default" => "1 / 3",
                            "desc"    => "",
                        ),
                        "column_content" => array(
                            "title"   => "Lorem ipsum dolor set",
                            "type"    => "textArea",
                            "holder"  => "Lorem ipsum dolor set",
                            "default" => "Lorem ipsum dolor set",
                            "desc"    => "Lorem ipsum dolor set",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
        ),
    ),
    "content" => array(
        "name" => "Content",
        "size" => "size-1-1",
        "only" => "builder",
        "settings" => array(
            "description" => array(
                "title"   => "This element displays content of your Core Editor",
                "type"    => "",
                "data"    => array(),
                "default" => "",
                "desc"    => "",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
	"counter" => array(
        "name" => "Counter",
        "size" => "size-1-4",
        "settings" => array(
            "style" => array(
                "title"   => "Choose Counter Style",
                "type"    => "select",
                "options" => array("style1"=>"Style 1","style2"=>"Style 2","style3"=>"Style 3"),
                "hide"    => array("style1"=>"fa,fa_icon","style2"=>" ","style3" =>"fa, fa_icon"),
                "default" => "",
                "desc"    => "",
            ),
			"fa" => array(
				"title"   => "Add Icon",
				"type"    => "fa",
				"holder"  => "",
				"default" => "",
				"desc"    => "",
			),
			"fa_icon" => array(
				"title"   => "Icon",
				"type"    => "hidden",
				"holder"  => "",
				"default" => "icon-umbrella",
				"desc"    => "Icon.",
			),
			"counter_number" => array(
                "title"   => "Counter number",
                "type"    => "text",
                "holder"  => "350",
                "default" => "350",
                "desc"    => "field to enter the counter number",
            ),
            "counter_description" => array(
                "title"   => "Counter description",
                "type"    => "text",
                "holder"  => "Features Added",
                "default" => "Features Added",
                "desc"    => "field description of the counter",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "divider" => array(
        "name" => "Divider",
        "size" => "size-1-1",
        "settings" => array(
            "type" => array(
                "title"   => "Choose Divider Type",
                "type"    => "select",
                "options" => array("light"=>"Light","dark"=>"Dark","colored"=>"Colored","with_dot"=>"With dot"),
                "hide"    => array("colored"=>" ","dark"=>"color","light" =>"color","with_dot" =>"color"),
                "default" => "",
                "desc"    => "",
            ),
            "color" => array(
                "title"   => "Choose Divider Color",
                "type"    => "color",
                "holder"  => "#01a9da",
                "default" => "#01a9da",
                "desc"    => "Choose divider color.",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "30px",
                "desc"    => "",
            ),
        ),
    ),
	"gallery" => array(
		"name"    => "Gallery",
		"size"    => "size-1-1",
		"settings" => array(
			"type" => array(
				"title" => "",
				"type" => "select",
				"options" => array("slide" => "Slide", "three_cols" => "3 Columns", "four_cols" => "4 Columns", "five_cols" => "5 Columns"),
				"default" => "success",
				"desc" => "",
			),
			"padding" => array(
				"title" => "",
				"type" => "text",
				"default" => "0",
				"desc" => "Padding for your Images",
			),
			"add_gallery" => array(
				"title" => "",
				"type" => "button",
				"save_to" => "gallery_list",
				"default" => "Edit Gallery",
				"desc" => "",
			),
			"gallery_list" => array(
				"title" => "",
				"type" => "gallery",
				"holder" => "",
				"default" => "",
				"desc" => "",
			),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
		),
	),
	"google_map" => array(
        "name"    => "Google Map",
        "size"    => "size-1-3",
        "content" => "google_map_embed",
        "settings" => array(
			"map_height" => array(
                "title"   => "Map Height",
                "type"    => "text",
                "holder"  => "",
                "default" => "420",
                "desc"    => "",
            ),
			"map_address" => array(
                "title"   => "Address",
                "type"    => "text",
                "holder"  => "",
                "default" => "New York",
                "desc"    => "",
            ),
			"map_marker" => array(
                "title"   => "Thumbnail Image",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Map Marker",
            ),
			"add_map_marker" => array(
                "title"   => "",
                "type"    => "button",
                "save_to" => "map_marker",
                "default" => "Upload",
                "desc"    => "",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
	"heading" => array(
        "name" => "Heading",
        "size" => "size-1-1",
		"only" => "builder",
        "settings" => array(
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "dropcap" => array(
        "name" => "Dropcap",
        "only" => "shortcode", //builder
        "content" => "text",
        "settings" => array(
            "text" => array(
                "title"   => "Dropcap Text",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert dropcap text.",
            ),
            "color" => array(
                "title"   => "Dropcap Color",
                "type"    => "color",
                "holder"  => "#02b5e0",
                "default" => "#02b5e0",
                "desc"    => "Choose dropcap background color.",
            ),
            "style" => array(
                "title"   => "Dropcap Style",
                "type"    => "select",
                "options" => array("square"=>"Square","circle"=>"Circle"),
                "holder"  => "",
                "default" => "square",
                "desc"    => "Choose dropcap color.",
            ),
        ),
    ),
    "fontawesome" => array(
        "name"    => "Font Awesome",
        "only" => "shortcode",
        "size"    => "size-1-3",
        "settings" => array(
            "fa" => array(
                "title"   => "Add Icon",
                "type"    => "fa",
                "holder"  => "",
                "default" => "",
                "desc"    => "",
            ),
            "fa_icon" => array(
                "title"   => "Icon",
                "type"    => "hidden",
                "holder"  => "",
                "default" => "icon-umbrella",
                "desc"    => "Icon.",
            ),
        ),
    ),
	"full_width" => array(
		"name"    => "Full Width start",
        "only" => "builder",
        "size"    => "size-1-1",
		"min-size" => "size-1-1",
        "settings" => array(
			"full_width_custom_class" => array(
				"title"		  => "Custom Class",
				"type" 		  => "text",
				"holder" 	  => "",
				"default" 	  => "",
				"desc" 		  => "",
			),
			"full_width_custom_id" => array(
				"title"		  => "Custom ID",
				"type" 		  => "text",
				"holder" 	  => "",
				"default"	  => "",
				"desc" 		  => "ID will help you build One Page, Example: if you inserted about here then use the Menu section to yourwebsite.com/#about etc",
			),
			"background_color" => array(
				"title" 	  => "Background color",
				"type" 		  => "color",
				"holder"	  => "",
				"default" 	  => "",
				"desc" 		  => "Choose background color.",
			),
			"image_thumb" => array(
                "title"   => "Thumbnail Image",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "The image.",
            ),
			"add_image_thumb" => array(
                "title"   => "",
                "type"    => "button",
                "save_to" => "image_thumb",
                "default" => "Upload",
                "desc"    => "",
            ),
			"background_style" => array(
				"title" 	  => "Background image style",
				"type" 		  => "select",
				"options" 	  => array("scroll" => "Scroll", "fixed" => "Fixed", "parallax" => "Parallax", "pattern" => "Pattern"),
				"default" 	  => "",
				"desc"		  => "",
			),
			"contrast" => array(
				"title"		  => "Container Color Scheme",
				"type" 		  => "select",
				"options"  	  => array('dark' => 'Dark', 'light' => 'Light'),
				"default" 	  => "light",
				"desc"		  => "",
			),
			"padding_top" => array(
				"title" 	  => "Container Padding Top",
				"type" 		  => "text",
				"holder" 	  => "",
				"default" 	  => "50px",
				"desc" 		  => "Controlling Container top margin value.",
			),
			"padding_bottom" => array(
				"title" 	  => "Container Padding Bottom",
				"type" 		  => "text",
				"holder" 	  => "",
				"default" 	  => "50px",
				"desc" 		  => "Those options will helps you insert images with no space top or bottom from container.",
			),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
		),
	),
	"full_width_end" => array(
		"name"    	=> "Full Width end",
        "only" 		=> "builder",
        "size"    	=> "size-1-1",
		"min-size"  => "size-1-1",
        "settings"  => array(
			"full_width_end_custom_class" => array(
				"desc" 		  => "The 'Full Width end' module is integral part of 'Full Width start' module. Those modules can not work separately.",
			),
		),
	),
    "label" => array(
        "name" => "Label",
        "only" => "shortcode",
        "content" => "text",
        "settings" => array(
            "text" => array(
                "title"   => "Label Text",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert label text.",
            ),
            "color" => array(
                "title"   => "Label Color",
                "type"    => "color",
                "holder"  => "",
                "default" => "",
                "desc"    => "Choose label color.",
            ),
        ),
    ),
	"image" => array(
        "name"    => "Image",
        "size"    => "size-1-3",
        "content" => "text",
        "settings" => array(
            "image_thumb" => array(
                "title"   => "Thumbnail Image",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "The image.",
            ),
			"add_image_thumb" => array(
                "title"   => "",
                "type"    => "button",
                "save_to" => "image_thumb",
                "default" => "Upload",
                "desc"    => "",
            ),
            "image_link" => array(
                "title"   => "Path for link",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "If the reference field is left blank, the redirection will not happen with pictures. Example: http://www.evatheme.com",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "message_box" => array(
        "name"    => "Message Box",
		"size" => "size-1-2",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title"   => "",
                "type"    => "button",
                "data"    => array("item"=>"message_box","settings"=>"items"),
                "default" => "Add Message Box",
                "desc"    => "",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "type",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "type" => array(
                            "title"   => "Choose Alert Box Style",
                            "type"    => "select",
                            "options" => array("warning"=>"Warning","info"=>"Info","success"=>"Success","error"=>"Error"),
                            "default" => "default",
                            "desc"    => "Message Box Type.",
                        ),
                        "message_title" => array(
                            "title"   => "Box Title",
                            "type"    => "text",
                            "holder"  => "Insert here Box Title",
                            "default" => "Title",
                            "desc"    => "Insert here Box Title",
                        ),
						"message_content" => array(
                            "title"   => "",
                            "type"    => "textArea",
                            "holder"  => "Insert here Box Content",
                            "default" => "Insert here Box Content",
                            "desc"    => "",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
	"partner" => array(
        "name" => "Partners",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "row-type" => "row",
        "only" => "builder",
        "settings" => array(
            "part_category" => array(
                "title"   => "Choose Partner category",
                "type"    => "category",
                "options" => $part_categories,
                "default" => "0",
                "desc"    => "Chosen categories will be displayed.",
            ),
            "category_ids" => array(
                "type"    => "hidden",
                "selector"=> "part_category",
                "default" => "",
            ),
			"style" => array(
                "title"   => "Select style",
                "type"    => "select",
                "options" => array('default'=>'Default','carousel'=>'Carousel'),
				"hide"    => array('default'=>'read_more','carousel'=>'items_per_line,read_more'),
                "default" => "default",
                "desc"    => "",
            ),
            "count" => array(
                "title"   => "Count",
                "type"    => "text",
                "holder"  => "12",
                "default" => "12",
                "desc"    => "",
            ),
			"items_per_line" => array(
                "title"   => "Items per line",
                "type"    => "text",
                "holder"  => "6",
                "default" => "6",
                "desc"    => "",
            ),
			/*
			"read_more" => array(
                "title"   => "Items per line",
                "type"    => "text",
                "holder"  => "6",
                "default" => "6",
                "desc"    => "",
            ),
			*/
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "portfolio" => array(
        "name" => "Portfolio",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "row-type" => "row",
		"only" => "builder",
        "settings" => array(
            "port_category" => array(
                "title"   => "Choose Portfolio category",
                "type"    => "category",
                "options" => $port_categories,
                "default" => "0",
                "desc"    => "Chosen categories will be included.",
            ),
            "category_ids" => array(
                "type"    => "hidden",
                "selector"=> "port_category",
                "default" => "",
            ),
			"wrapper" => array(
                "title"   => "Select style",
                "type"    => "select",
                "options" => array('wrap_container'=>'Default','full_width'=>'Full Width','carousel'=>'Carousel'),
				"hide"    => array('wrap_container'=>'more_text2','full_width'=>'more_text2,height','carousel'=>'pagination,column,filter'),
                "default" => "wrap_container",
                "desc"    => "",
            ),
            "column" => array(
                "title"   => "Column count",
                "type"    => "select",
                "options" => array('2'=>'2 Columns','3'=>'3 Columns','4'=>'4 Columns','5'=>'5 Columns'),
                "default" => "4",
                "desc"    => "This option will only 3 Column width when you are using portfolio with Sidebar. (Not a Fullwidth layout)",
            ),
			"layout" => array(
				"title" => "Layout",
				"type" => "select",
				"options" => array('deafult'=>'Default (Text and Spaces)','with_spaces'=>'Style with Spaces','without_spaces'=>'Style without Spaces'),
				"default" => "deafult",
			),
            "count" => array(
                "title"   => "Count",
                "type"    => "text",
                "holder"  => "10",
                "default" => "10",
                "desc"    => "",
            ),
            "height" => array(
                "title"   => "Height",
                "type"    => "text",
                "holder"  => "250",
                "default" => "",
                "desc"    => "Portfolio item height",
            ),
            "filter" => array(
                "title"   => "Display Filter?",
                "type"    => "select",
                "options" => $arrayYesNo,
                "default" => "true",
                "desc"    => "",
            ),
            "pagination" => array(
                "title"   => "Display Pagination?",
                "type"    => "select",
                "options" => array('none'=>'None','simple'=>'Simple pagination', 'infinite'=>'Infinite scroll'),
                "default" => "true",
                "desc"    => "",
            ),
			"order" => array(
				"title" => "Order",
				"type" => "select",
				"options" => array('date_desc'=>'Date Desc','date_asc'=>'Date Asc','title_desc'=>'Title Desc','title_asc'=>'Title Asc','random'=>'Random'),
				"default" => "date_desc",
				"desc" => "",
			),
			/*
			"more_text2" => array(
                "title"   => "Read more text",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "Insert custom 'Read More' text",
            ),
			*/
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "pricing_table" => array(
        "name"    => "Pricing Table",
        "size"    => "size-1-3",
        "content" => "items",
		"only" => "builder",
        "settings" => array(
            "add_item" => array(
                "title"   => "Add Price Item",
                "type"    => "button",
                "data"    => array("item"=>"pricing_table","settings"=>"items"),
                "default" => "Add Price Item",
                "desc"    => "",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "item_title",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "item_title" => array(
                            "title"   => "Name",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_price" => array(
                            "title"   => "Price",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_period" => array(
                            "title"   => "Period",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_information_field1" => array(
                            "title"   => "Information field",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_information_field2" => array(
                            "title"   => "Information field",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_information_field3" => array(
                            "title"   => "Information field",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_information_field4" => array(
                            "title"   => "Information field",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_get_it_now" => array(
                            "title"   => "'Get it now' Link",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
						"item_caption" => array(
                            "title"   => "'Get it now' caption",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
                        "item_expand" => array(
                            "title"   => "Most popular",
                            "type"    => "checkbox",
                            "default" => "false",
                            "desc"    => "",
                        ),
						"new_item" => array(
                            "title"   => "New item",
                            "type"    => "checkbox",
                            "default" => "false",
                            "desc"    => "",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "progress" => array(
        "name"    => "Progress Bar",
        "size"    => "size-1-3",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title"   => "",
                "type"    => "button",
                "data"    => array("item"=>"progress","settings"=>"items"),
                "default" => "Add Progress Bar",
                "desc"    => "",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "progress_title",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "progress_title" => array(
                            "title"   => "",
                            "type"    => "text",
                            "holder"  => "Progress title",
                            "default" => "Progress title",
                            "desc"    => "",
                        ),
                        "percent" => array(
                            "title"   => "Progress Percent",
                            "type"    => "text",
                            "holder"  => "Progress percent",
                            "default" => "50",
                            "desc"    => "integer value in 0-100.",
                        ),
                        "type" => array(
                            "title"   => "Choose Type",
                            "type"    => "select",
                            "options" => array("line"=>"Linear Skills","circle"=>"Circular Skills"),
                            "desc"    => "Style of Progress",
                        ),
                        "color" => array(
                            "title"   => "Color of Progress",
                            "type"    => "color",
                            "holder"  => "Color of Progress",
                            "default" => "#333333",
                            "desc"    => "",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
	"promo_text" => array(
        "name" => "Promo Text",
        "size" => "size-1-1",
        "content" => "promo_text_content",
		"only" => "builder",
        "settings" => array(
            "type" => array(
				"title"   => "Choose Style",
				"type"    => "select",
				"options" => array("white_style"=>"White Style","black_style"=>"Black Style"),
				"desc"    => "Style of Promo Text",
			),
			"promo_text_content" => array(
                "title"   => "Main text",
                "type"    => "textArea",
                "holder"  => "",
                "default" => 'Responsive Multi-Purpose WordPress Theme',
                "desc"    => "",
            ),
            "description" => array(
                "title"   => "Additional text",
                "type"    => "textArea",
                "holder"  => "This is promo text description section",
                "default" => 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut.',
                "desc"    => "",
            ),
            "btn_text" => array(
                "title"   => "",
                "type"    => "text",
                "holder"  => "button text",
                "default" => "Purchase Now",
                "desc"    => "You can insert custom Read More text",
            ),
            "btn_color" => array(
                "title"   => "",
                "type"    => "color",
                "holder"  => "",
                "default" => "",
                "desc"    => "Choose button background color",
            ),
            "btn_url" => array(
                "title"   => "",
                "type"    => "text",
                "holder"  => "Only URL here",
                "default" => "www.evatheme.com",
                "desc"    => "Read More Link URL",
            ),
            "btn_target" => array(
                "title"   => "",
                "type"    => "select",
                "options" => $linkTarget,
                "default" => "_blank",
                "desc"    => "Blank is opened new windows. Self is opened current windows.",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "service" => array(
        "name"    => "Service",
        "size"    => "size-1-3",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title"   => "",
                "type"    => "button",
                "data"    => array("item"=>"service","settings"=>"items"),
                "default" => "Add Service",
                "desc"    => "",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "title",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "service_style" => array(
                            "title"   => "",
                            "type"    => "select",
                            "options" => array('style1' => 'Style 1','style2' => 'Style 2','style3' => 'Style 3','style4' => 'Style 4'),
                            "default" => "style_2",
                            "desc"    => "Choose your style.",
                        ),
                        "fa" => array(
                            "title"   => "Add Icon",
                            "type"    => "fa",
                            "holder"  => "",
                            "default" => "",
                            "desc"    => "",
                        ),
                        "fa_icon" => array(
                            "title"   => "Icon",
                            "type"    => "hidden",
                            "holder"  => "",
                            "default" => "icon-umbrella",
                            "desc"    => "Icon.",
                        ),
                        "title" => array(
                            "title"   => "",
                            "type"    => "text",
                            "holder"  => "Your Service Title",
                            "default" => "Your Service Title",
                            "desc"    => "Insert Service Title.",
                        ),
                        "content" => array(
                            "title"   => "",
                            "type"    => "textArea",
                            "holder"  => "Column Content",
                            "default" => "Column Content",
                            "desc"    => "",
                        ),
                        "more_url" => array(
                            "title"   => "",
                            "type"    => "text",
                            "holder"  => "Only URL here",
                            "default" => "",
                            "desc"    => "Read More URL.",
                        ),
                        "more_target" => array(
                            "title"   => "",
                            "type"    => "select",
                            "options" => $linkTarget,
                            "default" => "_blank",
                            "desc"    => "Blank is opened new windows. Self is opened current windows.",
                        ),
						"padding_bottom_module" => array(
							"title"   => "Bottom padding for the module",
							"type"    => "text",
							"holder"  => "",
							"default" => "50px",
							"desc"    => "",
						),
                    ),
                ),
                "desc"    => "Items",
            ),
        ),
    ),
    "sidebar" => array(
        "name" => "Sidebar",
        "size" => "size-1-4",
        "only" => "builder",
        "settings" => array(
            "name" => array(
                "title"   => "",
                "type"    => "select",
                "options" => $arraySidebar,
                "default" => "Default sidebar",
                "desc"    => "Please creat your own Sidebar in Theme Options Sidebar Creater then Choose here.",
            ),
        ),
    ),
    "slider" => array(
        "name" => "Slider",
        "size" => "size-1-1",
        "settings" => array(
            "id" => array(
                "title"   => "Choose the Slider",
                "type"    => "select",
                "options" => $arraySlider,
                "default" => "0",
                "desc"    => "Your created Sliders will be displayed here. Including LayersSlider and all of our used sliders.",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "tab" => array(
        "name"    => "Tab",
        "size"    => "size-1-3",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title"   => "",
                "type"    => "button",
                "data"    => array("item"=>"tab","settings"=>"items"),
                "default" => "Add Tab",
                "desc"    => "",
            ),
            "position" => array(
                "title"   => "Choose Tab position",
                "type"    => "select",
                "options" => array("top"=>"Top","left"=>"Left"),
                "default" => "top",
                "desc"    => "Tab Titles can be displayed top, left position.",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "title",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "title" => array(
                            "title"   => "",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "Tab Title",
                            "desc"    => "",
                        ),
                        "item_content" => array(
                            "title"   => "",
                            "type"    => "textArea",
                            "holder"  => "Tab Content",
                            "default" => "Tab Content",
                            "desc"    => "",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "team" => array(
        "name" => "Team",
        "size" => "size-1-1",
        "min-size" => "size-1-1",
        "row-type" => "row",
        "only" => "builder",
        "settings" => array(
            "team_category" => array(
                "title"   => "Choose Team category",
                "type"    => "category",
                "options" => $team_categories,
                "default" => "0",
                "desc"    => "Chosen categories will be displayed.",
            ),
            "category_ids" => array(
                "type"    => "hidden",
                "selector"=> "team_category",
                "default" => "",
            ),
            "count" => array(
                "title"   => "Count",
                "type"    => "text",
                "holder"  => "4",
                "default" => "4",
                "desc"    => "",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "testimonials" => array(
        "name" => "Testimonials",
        "size" => "size-1-1",
		"only" => "builder",
        "settings" => array(
            "testim_category" => array(
                "title"   => "Choose Testimonials category",
                "type"    => "category",
                "options" => $testim_categories,
                "default" => "0",
                "desc"    => "Chosen categories will be displayed.",
            ),
            "category_ids" => array(
                "type"    => "hidden",
                "selector"=> "testim_category",
                "default" => "",
            ),
			"style" => array(
                "title"   => "Select style",
                "type"    => "select",
                "options" => array('columns'=>'Columns','full_width'=>'Full width','carousel'=>'Carousel'),
                "default" => "columns",
                "desc"    => "",
            ),
            "count" => array(
                "title"   => "Count",
                "type"    => "text",
                "holder"  => "9",
                "default" => "9",
                "desc"    => "",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "toggle" => array(
        "name"    => "Toggle",
        "size"    => "size-1-3",
        "content" => "items",
        "settings" => array(
            "add_item" => array(
                "title"   => "",
                "type"    => "button",
                "data"    => array("item"=>"toggle","settings"=>"items"),
                "default" => "Add Toggle",
                "desc"    => "",
            ),
            "items" => array(
                "title"     => "Items",
                "type"      => "container",
                "container_type"=> "toggle",
                "title_as"  => "item_title",
                "add_button"=> "add_item",
                "default" => array(
                    array(
                        "item_title" => array(
                            "title"   => "",
                            "type"    => "text",
                            "holder"  => "",
                            "default" => "Toggle Title",
                            "desc"    => "",
                        ),
                        "item_expand" => array(
                            "title"   => "Expand?",
                            "type"    => "checkbox",
                            "default" => "false",
                            "desc"    => "",
                        ),
                        "item_content" => array(
                            "title"   => "",
                            "type"    => "textArea",
                            "holder"  => "Toggle Content",
                            "default" => "Toggle Content",
                            "desc"    => "",
                        ),
                    )
                ),
                "desc"    => "Items",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
    "video" => array(
        "name"    => "Video",
        "size"    => "size-1-3",
        "content" => "video_embed",
        "settings" => array(
            "insert_type" => array(
                "title"   => "Choose Post type",
                "type"    => "select",
                "options" => array("type_url" => "URL", "type_embed" => "Embed"),
                "hide"    => array("type_url" => "video_embed", "type_embed" => "video_m4v,add_video,video_thumb,add_thumb"),
                "default" => "post",
                "desc"    => "Chosen Post type will be displayed.",
            ),
            "video_m4v" => array(
                "title"   => "M4V File URL",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "The URL to the .m4v video file.",
            ),
            "add_video" => array(
                "title"   => "",
                "type"    => "button",
                "save_to" => "video_m4v",
                "default" => "Upload",
                "desc"    => "",
            ),
            "video_thumb" => array(
                "title"   => "Video Thumbnail Image",
                "type"    => "text",
                "holder"  => "",
                "default" => "",
                "desc"    => "The preivew image.",
            ),
            "add_thumb" => array(
                "title"   => "",
                "type"    => "button",
                "save_to" => "video_thumb",
                "default" => "Upload",
                "desc"    => "",
            ),
            "video_embed" => array(
                "title"   => "Embeded Code",
                "type"    => "textArea",
                "holder"  => "",
                "default" => "",
                "desc"    => "If you're not using self hosted video then you can include embeded code here.",
            ),
			"padding_bottom_module" => array(
                "title"   => "Bottom padding for the module",
                "type"    => "text",
                "holder"  => "",
                "default" => "50px",
                "desc"    => "",
            ),
        ),
    ),
);
?>
